
export const APP_STATUS_RESET = "APP_STATUS_RESET";
export const APP_STATUS_SUCCESS = "APP_STATUS_SUCCESS";
export const APP_STATUS_FAILED = "APP_STATUS_FAILED";
export const APP_STATUS_LOADING = "APP_STATUS_LOADING";
export const APP_STATUS_FETCHING = "APP_STATUS_FETCHING";

export const APP_STATUS_REDIRECT = "APP_STATUS_REDIRECT";
